web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./public:/public
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./public:/public
